name: Test Project
on : push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses : actions/checkout@v6
      - name: Install dependencies (root)
        run: npm ci
      - name: Install dependencies (server)
        run: cd server && npm ci
      - name: Install dependencies (client)
        run: cd client && npm ci
      - name : Run project
        run: npm run dev
